name: reviewdog
on: [pull_request]
jobs:
  golangci-lint-github-pr-review:
    name: runner / golangci-lint (github-pr-review)
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
      - name: golangci-lint w/ github-pr-review
        uses: reviewdog/action-golangci-lint@v2 
        with:
          golangci_lint_flags: "./testdata"
          tool_name: "golangci-lint-github-pr-review"
          reporter: "github-pr-review"

  golangci-lint-github-check:
    name: runner / golangci-lint (github-check)
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
      - name: golangci-lint w/ github-check
        uses: reviewdog/action-golangci-lint@v2
        with:
          golangci_lint_flags: "./testdata"
          tool_name: "golangci-lint-github-check"
          level: warning
          reporter: "github-check"
